# Generated by Django 4.1.2 on 2022-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zurimodel',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='zurimodel',
            name='backend',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zurimodel',
            name='slackUsername',
            field=models.CharField(default='ItsWeshy', max_length=200),
        ),
    ]
